name: Selenium Automation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Chrome browser
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget -N https://chromedriver.storage.googleapis.com/97.0.4692.20/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

    - name: Build with Maven
      run: ./mvnw clean test

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

    - name: Clean up Chrome processes
      run: sudo pkill chrome
