name: GeekTimeMain
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run_selenium_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Selenium Script
        run: java -jar out/artifacts/geekauto_jar/geekauto.jar
